PotatRaycer: Texture Class Reference
Texture Class Reference
Class used to create a Texture.
#include <Texture.hpp>
Public Member Functions
Texture (const std::string &filename)
~Texture ()
Vec3 sample (float u, float v) const
Get the color of the texture.
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec, const std::vector< std::shared_ptr< IHitable >> &_world) const
Function know if the ray hit the object.
bool scatter (const Ray &r_in, const hit_record_t &rec, Vec3 &attenuation, Ray &scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> &_obj) const override
Function to scatter the ray.
std::string getName () const override final
Function to get the name of the material.
Public Member Functions inherited from IMaterial
virtual ~IMaterial ()=default
Private Attributes
unsigned char * data
int width
int height
int channels
Detailed Description
Class used to create a Texture.
Definition at line 26 of file Texture.hpp.
Constructor & Destructor Documentation
Texture()
Texture::Texture (const std::string & filename) inline
Definition at line 31 of file Texture.hpp.
{
             data = stbi_load(filename.c_str(), &width, &height, &channels, 0);
             if (!data) {
                 std::cerr << "Error: Could not load texture file " << filename << std::endl;
                 width = height = channels = 0;
             }
         }
References channels, data, height, and width.
~Texture()
Texture::~Texture () inline
Definition at line 38 of file Texture.hpp.
                    {
             // stbi_image_free(data);
         }
Member Function Documentation
getName()
std::string Texture::getName () const final override virtual
Function to get the name of the material.
Returns
The name of the material.
Implements IMaterial.
Definition at line 92 of file Texture.cpp.
 {
     return "Texture";
 }
hit()
bool Texture::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec, const std::vector< std::shared_ptr< IHitable >> & _world) const
Function know if the ray hit the object.
Parameters
r The ray
t_min The minimum value of t
t_max The maximum value of t
rec The hit record
_world The objects in the scene
Returns
True if the ray hit the object, false otherwise
Definition at line 40 of file Texture.cpp.
 {
     hit_record_t temp_rec;
     bool hit_anything = false;
     double closest_so_far = t_max;
     for(int i = 0; i < _world.size(); i++) {
         if (_world[i]->hit(r,t_min,closest_so_far,temp_rec)) {
             hit_anything = true;
             closest_so_far = temp_rec.t;
             rec = temp_rec;
         }
     }
     return hit_anything;
 }
Referenced by scatter().
sample()
Vec3 Texture::sample (float u, float v) const
Get the color of the texture.
Parameters
u The u value.
v The v value.
Returns
The color of the texture.
Definition at line 15 of file Texture.cpp.
 {
     if (!data) return Vec3(0, 0, 0);
     u = fmod(u, 1.0f);
     v = fmod(v, 1.0f);
     if (u < 0) u += 1.0f;
     if (v < 0) v += 1.0f;
     int x = static_cast<int>(u * width);
     int y = static_cast<int>((1.0f - v) * height);
     x = std::min(x, width - 1);
     y = std::min(y, height - 1);
     int pixelIndex = (y * width + x) * channels;
     if (channels == 3 || channels == 4) {
         return Vec3::fromRGB(data[pixelIndex], data[pixelIndex + 1], data[pixelIndex + 2]);
     } else if (channels == 1) {
         return Vec3::fromRGB(data[pixelIndex], data[pixelIndex], data[pixelIndex]);
     } else {
         return Vec3(1, 0, 1);
     }
 }
References channels, data, Vec3::fromRGB(), height, and width.
Referenced by scatter().
scatter()
bool Texture::scatter (const Ray & r_in, const hit_record_t & rec, Vec3 & attenuation, Ray & scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> & _obj) const override virtual
Function to scatter the ray.
Parameters
r_in The ray.
rec The hit record.
attenuation The attenuation.
scattered The scattered ray.
light The light.
_obj The objects in the scene.
Returns
True if the ray has been scattered, false otherwise.
Implements IMaterial.
Definition at line 64 of file Texture.cpp.
 {
     Vec3 lightDir;
     if (!light->getType().compare("Directional")) {
         lightDir = light->calculateLightDirection(rec.p);
     } else {
         lightDir = light->getNormal();
         lightDir.make_unit_vector();
     }
     Vec3 shadowRayOrigin = rec.p;
     Vec3 shadowRayDirection = lightDir;
     Ray shadowRay(shadowRayOrigin, shadowRayDirection);
     hit_record_t shadowRec;
     if (hit(shadowRay, 0.001, MAXFLOAT, shadowRec, _obj)) {
         attenuation = Vec3(0, 0, 0);
         return false;
     } else {
         Vec3 textureColor = this->sample(rec.uv.e[0], rec.uv.e[1]);
         float cos_theta = fabs(dot(rec.normal, lightDir));
         attenuation = textureColor * cos_theta;
         Vec3 reflected = reflect(unit_vector(r_in.getDirection()), rec.normal);
         scattered = Ray(rec.p, reflected + random_in_unit_sphere());
         return true;
     }
 }
References dot(), Ray::getDirection(), hit(), Vec3::make_unit_vector(), random_in_unit_sphere(), reflect(), sample(), and unit_vector().
Member Data Documentation
channels
int Texture::channels private
Definition at line 28 of file Texture.hpp.
Referenced by sample(), and Texture().
data
unsigned char* Texture::data private
Definition at line 27 of file Texture.hpp.
Referenced by sample(), and Texture().
height
int Texture::height private
Definition at line 28 of file Texture.hpp.
Referenced by sample(), and Texture().
width
int Texture::width private
Definition at line 28 of file Texture.hpp.
Referenced by sample(), and Texture().
The documentation for this class was generated from the following files:
src/Materials/Stb_texture/Texture.hpp
src/Materials/Stb_texture/Texture.cpp