PotatRaycer: AmbiantLight Class Reference
AmbiantLight Class Reference
#include <AmbiantLight.hpp>
Public Member Functions
AmbiantLight (Vec3 position, float intensity)
~AmbiantLight ()
std::string getType () override final
float getIntensity () const override final
Vec3 getPosition () const override final
Vec3 calculateLightDirection (const Vec3 &point) const override final
Vec3 getNormal () override final
float getSize () override final
Public Member Functions inherited from ILight
virtual ~ILight ()=default
Private Attributes
std::string _type = "ambiant"
Vec3 position
float intensity
Detailed Description
Definition at line 13 of file AmbiantLight.hpp.
Constructor & Destructor Documentation
AmbiantLight()
AmbiantLight::AmbiantLight (Vec3 position, float intensity)
Definition at line 14 of file AmbiantLight.cpp.
                                                          : position(position), intensity(intensity)
 {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "Log: Ambiant Light created with parameters pos = " << position << ", i = " << intensity << ".";
     logger->log(INFO, msg.str());
 }
References LoggerSingleton::getInstance(), INFO, intensity, Logger::log(), and position.
~AmbiantLight()
AmbiantLight::~AmbiantLight ()
Definition at line 10 of file AmbiantLight.cpp.
 {
 }
Member Function Documentation
calculateLightDirection()
Vec3 AmbiantLight::calculateLightDirection (const Vec3 & point) const final override virtual
Implements ILight.
Definition at line 37 of file AmbiantLight.cpp.
 {
     return unit_vector(position - point);
 }
References position, and unit_vector().
getIntensity()
float AmbiantLight::getIntensity () const final override virtual
Implements ILight.
Definition at line 32 of file AmbiantLight.cpp.
 {
     return intensity;
 }
References intensity.
getNormal()
Vec3 AmbiantLight::getNormal () final override virtual
Implements ILight.
Definition at line 42 of file AmbiantLight.cpp.
 {
     return Vec3(0, 0, 0);
 }
getPosition()
Vec3 AmbiantLight::getPosition () const final override virtual
Implements ILight.
Definition at line 27 of file AmbiantLight.cpp.
 {
     return position;
 }
References position.
getSize()
float AmbiantLight::getSize () final override virtual
Implements ILight.
Definition at line 47 of file AmbiantLight.cpp.
 {
     return 0;
 }
getType()
std::string AmbiantLight::getType () final override virtual
Implements ILight.
Definition at line 22 of file AmbiantLight.cpp.
 {
     return _type;
 }
References _type.
Member Data Documentation
_type
std::string AmbiantLight::_type = "ambiant" private
Definition at line 24 of file AmbiantLight.hpp.
Referenced by getType().
intensity
float AmbiantLight::intensity private
Definition at line 26 of file AmbiantLight.hpp.
Referenced by AmbiantLight(), and getIntensity().
position
Vec3 AmbiantLight::position private
Definition at line 25 of file AmbiantLight.hpp.
Referenced by AmbiantLight(), calculateLightDirection(), and getPosition().
The documentation for this class was generated from the following files:
src/Light/Ambiant/AmbiantLight.hpp
src/Light/Ambiant/AmbiantLight.cpp