PotatRaycer: Vec3 Class Reference
Vec3 Class Reference
Class for representing a 3D vector.
#include <Vec3.hpp>
Public Member Functions
Vec3 ()
Default constructor for Vec3.
Vec3 (float e0, float e1, float e2)
Parameterized constructor for Vec3.
float x () const
Get the x-coordinate of the vector.
float y () const
Get the y-coordinate of the vector.
float z () const
Get the z-coordinate of the vector.
float r () const
Get the red component (same as x-coordinate).
float g () const
Get the green component (same as y-coordinate).
float b () const
Get the blue component (same as z-coordinate).
const Vec3 & operator+ () const
Unary plus operator.
Vec3 operator- () const
Unary minus operator.
float operator[] (int i) const
Access element by index.
float & operator[] (int i)
Access element by index.
Vec3 & operator+= (const Vec3 &v)
Vec3 & operator-= (const Vec3 &v)
Vec3 & operator*= (const Vec3 &v)
Vec3 & operator/= (const Vec3 &v)
Vec3 & operator*= (const float t)
Vec3 & operator/= (const double t)
float length () const
Compute the length of the vector.
float length_squared () const
Compute the squared length of the vector.
void make_unit_vector ()
Normalize the vector to a unit vector.
Vec3 normalize ()
Return a normalized version of the vector.
Static Public Member Functions
static Vec3 fromRGB (unsigned char r, unsigned char g, unsigned char b)
Create a Vec3 from RGB values.
Public Attributes
float e [3]
Array storing the x, y, and z coordinates of the vector.
Detailed Description
Class for representing a 3D vector.
The Vec3 class provides various operations for 3-dimensional vectors, including initialization, scaling, addition, subtraction, normalization, and vector products.
Definition at line 26 of file Vec3.hpp.
Constructor & Destructor Documentation
Vec3() [1/2]
Vec3::Vec3 () inline
Default constructor for Vec3.
Initializes the vector with zero values.
Definition at line 33 of file Vec3.hpp.
 : e{0.0f, 0.0f, 0.0f} {}
Referenced by fromRGB(), normalize(), and operator-().
Vec3() [2/2]
Vec3::Vec3 (float e0, float e1, float e2) inline
Parameterized constructor for Vec3.
Parameters
e0 The x-coordinate of the vector.
e1 The y-coordinate of the vector.
e2 The z-coordinate of the vector.
Definition at line 42 of file Vec3.hpp.
{
         e[0] = e0;
         e[1] = e1;
         e[2] = e2;
     }
References e.
Member Function Documentation
b()
float Vec3::b () const inline
Get the blue component (same as z-coordinate).
Returns
The blue component.
Definition at line 88 of file Vec3.hpp.
 { return e[2]; }
References e.
Referenced by Compute::colorThread(), and fromRGB().
fromRGB()
static Vec3 Vec3::fromRGB (unsigned char r, unsigned char g, unsigned char b) inline static
Create a Vec3 from RGB values.
Parameters
r Red component (0-255).
g Green component (0-255).
b Blue component (0-255).
Returns
A Vec3 representing the color.
Definition at line 161 of file Vec3.hpp.
{
         return Vec3(r / 255.0f, g / 255.0f, b / 255.0f);
     }
References b(), g(), r(), and Vec3().
Referenced by Texture::sample().
g()
float Vec3::g () const inline
Get the green component (same as y-coordinate).
Returns
The green component.
Definition at line 81 of file Vec3.hpp.
 { return e[1]; }
References e.
Referenced by Compute::colorThread(), and fromRGB().
length()
float Vec3::length () const inline
Compute the length of the vector.
Returns
The length of the vector.
Definition at line 132 of file Vec3.hpp.
 { return sqrt(e[0]*e[0] + e[1]*e[1] + e[2]*e[2]); }
References e.
Referenced by normalize(), Dielectric::scatter(), Lambertian::scatter(), and unit_vector().
length_squared()
float Vec3::length_squared () const inline
Compute the squared length of the vector.
Returns
The squared length of the vector.
Definition at line 139 of file Vec3.hpp.
 { return e[0]*e[0] + e[1]*e[1] + e[2]*e[2]; }
References e.
Referenced by random_in_unit_sphere().
make_unit_vector()
void Vec3::make_unit_vector () inline
Normalize the vector to a unit vector.
Definition at line 178 of file Vec3.hpp.
{
     float k = 1.0 / sqrt(e[0]*e[0] + e[1]*e[1] + e[2]*e[2]);
     e[0] *= k; e[1] *= k; e[2] *= k;
 }
References e.
Referenced by Texture::scatter(), and Lambertian::scatter().
normalize()
Vec3 Vec3::normalize () inline
Return a normalized version of the vector.
Returns
A new normalized vector.
Definition at line 225 of file Vec3.hpp.
{
     float length = sqrt(e[0] * e[0] + e[1] * e[1] + e[2] * e[2]);
     return Vec3(e[0] / length, e[1] / length, e[2] / length);
 }
References e, length(), and Vec3().
Referenced by Triangle::hit().
operator*=() [1/2]
Vec3 & Vec3::operator*= (const float t) inline
Definition at line 258 of file Vec3.hpp.
{
     e[0] *= t;
     e[1] *= t;
     e[2] *= t;
     return *this;
 }
References e.
operator*=() [2/2]
Vec3 & Vec3::operator*= (const Vec3 & v) inline
Definition at line 244 of file Vec3.hpp.
{
     e[0] *= v.e[0];
     e[1] *= v.e[1];
     e[2] *= v.e[2];
     return *this;
 }
References e.
operator+()
const Vec3& Vec3::operator+ () const inline
Unary plus operator.
Returns
A constant reference to the vector.
Definition at line 95 of file Vec3.hpp.
 { return *this; }
operator+=()
Vec3 & Vec3::operator+= (const Vec3 & v) inline
Definition at line 230 of file Vec3.hpp.
{
     e[0] += v.e[0];
     e[1] += v.e[1];
     e[2] += v.e[2];
     return *this;
 }
References e.
operator-()
Vec3 Vec3::operator- () const inline
Unary minus operator.
Returns
A new vector with negated components.
Definition at line 102 of file Vec3.hpp.
 { return Vec3(-e[0], -e[1], -e[2]); }
References e, and Vec3().
operator-=()
Vec3 & Vec3::operator-= (const Vec3 & v) inline
Definition at line 237 of file Vec3.hpp.
{
     e[0] -= v.e[0];
     e[1] -= v.e[1];
     e[2] -= v.e[2];
     return *this;
 }
References e.
operator/=() [1/2]
Vec3& Vec3::operator/= (const double t) inline
Definition at line 125 of file Vec3.hpp.
 { return *this *= 1/t; }
operator/=() [2/2]
Vec3 & Vec3::operator/= (const Vec3 & v) inline
Definition at line 251 of file Vec3.hpp.
{
     e[0] /= v.e[0];
     e[1] /= v.e[1];
     e[2] /= v.e[2];
     return *this;
 }
References e.
operator[]() [1/2]
float& Vec3::operator[] (int i) inline
Access element by index.
Parameters
i Index of the element.
Returns
Reference to the element at index i.
Definition at line 118 of file Vec3.hpp.
 { return e[i]; }
References e.
operator[]() [2/2]
float Vec3::operator[] (int i) const inline
Access element by index.
Parameters
i Index of the element.
Returns
The element at index i.
Definition at line 110 of file Vec3.hpp.
 { return e[i]; }
References e.
r()
float Vec3::r () const inline
Get the red component (same as x-coordinate).
Returns
The red component.
Definition at line 74 of file Vec3.hpp.
 { return e[0]; }
References e.
Referenced by Compute::colorThread(), and fromRGB().
x()
float Vec3::x () const inline
Get the x-coordinate of the vector.
Returns
The x-coordinate.
Definition at line 53 of file Vec3.hpp.
 { return e[0]; }
References e.
Referenced by Camera::get_Ray().
y()
float Vec3::y () const inline
Get the y-coordinate of the vector.
Returns
The y-coordinate.
Definition at line 60 of file Vec3.hpp.
 { return e[1]; }
References e.
Referenced by Camera::get_Ray().
z()
float Vec3::z () const inline
Get the z-coordinate of the vector.
Returns
The z-coordinate.
Definition at line 67 of file Vec3.hpp.
 { return e[2]; }
References e.
Member Data Documentation
e
float Vec3::e[3]
Array storing the x, y, and z coordinates of the vector.
Definition at line 165 of file Vec3.hpp.
Referenced by b(), cross(), g(), length(), length_squared(), make_unit_vector(), normalize(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/=(), operator<<(), operator>>(), operator[](), r(), rotateVertex(), scaleVertex(), translateVertex(), Vec3(), x(), y(), and z().
The documentation for this class was generated from the following file:
src/Vec3/Vec3.hpp