PotatRaycer: FileWatcher Class Reference
FileWatcher Class Reference
Class for watching changes in configuration files.
#include <FileWatcher.hpp>
Public Member Functions
FileWatcher ()
~FileWatcher ()
void addObserver (IObserver *observer)
Add an observer to the list of observers.
void setFileToWatch (const std::string &fileToWatch)
Set the file to watch.
void removeObserver (IObserver *observer)
Remove an observer from the list of observers.
void notifyObservers (const std::string &message)
Notify all observers.
void startWatching ()
Start watching the file.
const std::string & getFile ()
Get the file to watch.
Private Member Functions
void handleEvents ()
Private Attributes
int fd
int wd
std::list< IObserver * > observers
std::string _file
Detailed Description
Class for watching changes in configuration files.
Definition at line 23 of file FileWatcher.hpp.
Constructor & Destructor Documentation
FileWatcher()
FileWatcher::FileWatcher () inline
Definition at line 32 of file FileWatcher.hpp.
 {}
~FileWatcher()
FileWatcher::~FileWatcher ()
Definition at line 15 of file FileWatcher.cpp.
 {
     inotify_rm_watch(fd, wd);
     close(fd);
 }
References fd, and wd.
Member Function Documentation
addObserver()
void FileWatcher::addObserver (IObserver * observer)
Add an observer to the list of observers.
Parameters
observer The observer to add.
Definition at line 21 of file FileWatcher.cpp.
 {
     observers.push_back(observer);
 }
References observers.
Referenced by Compute::loop().
getFile()
const std::string& FileWatcher::getFile () inline
Get the file to watch.
Returns
The file to watch.
Definition at line 68 of file FileWatcher.hpp.
         {
             return _file;
         }
References _file.
Referenced by Core::generatePPM().
handleEvents()
void FileWatcher::handleEvents () private
Definition at line 70 of file FileWatcher.cpp.
 {
     char buffer[1024 * (sizeof(struct inotify_event) + 16)];
     int length = read(fd, buffer, sizeof(buffer));
     if (length < 0) {
         perror("read");
         return;
     }
     int i = 0;
     while (i < length) {
         struct inotify_event *event = (struct inotify_event *)&buffer[i];
         if (event->mask & IN_MODIFY) {
             notifyObservers("Configuration file modified.");
         }
         i += sizeof(struct inotify_event) + event->len;
     }
 }
References fd, and notifyObservers().
Referenced by startWatching().
notifyObservers()
void FileWatcher::notifyObservers (const std::string & message)
Notify all observers.
Parameters
message The message to send to the observers.
Definition at line 31 of file FileWatcher.cpp.
 {
     for (IObserver* observer : observers) {
         observer->reset();
     }
 }
References observers.
Referenced by handleEvents().
removeObserver()
void FileWatcher::removeObserver (IObserver * observer)
Remove an observer from the list of observers.
Parameters
observer The observer to remove.
Definition at line 26 of file FileWatcher.cpp.
 {
     observers.remove(observer);
 }
References observers.
setFileToWatch()
void FileWatcher::setFileToWatch (const std::string & fileToWatch)
Set the file to watch.
Parameters
fileToWatch The file to watch.
Definition at line 38 of file FileWatcher.cpp.
 {
     _file = fileToWatch;
     fd = inotify_init();
     if (fd < 0) {
         perror("inotify_init");
         exit(EXIT_FAILURE);
     }
     wd = inotify_add_watch(fd, fileToWatch.c_str(), IN_MODIFY);
     if (wd == -1) {
         perror("inotify_add_watch");
         exit(EXIT_FAILURE);
     }
 }
References _file, fd, and wd.
Referenced by main().
startWatching()
void FileWatcher::startWatching ()
Start watching the file.
Definition at line 53 of file FileWatcher.cpp.
 {
     fd_set fds;
     FD_ZERO(&fds);
     FD_SET(fd, &fds);
     struct timeval timeout = {0, 0};
     int ret = select(fd + 1, &fds, NULL, NULL, &timeout);
     if (ret < 0) {
         perror("select");
         exit(EXIT_FAILURE);
     } else if (ret > 0) {
         if (FD_ISSET(fd, &fds)) {
             handleEvents();
         }
     }
 }
References fd, and handleEvents().
Referenced by Compute::loop().
Member Data Documentation
_file
std::string FileWatcher::_file private
Definition at line 29 of file FileWatcher.hpp.
Referenced by getFile(), and setFileToWatch().
fd
int FileWatcher::fd private
Definition at line 25 of file FileWatcher.hpp.
Referenced by handleEvents(), setFileToWatch(), startWatching(), and ~FileWatcher().
observers
std::list<IObserver*> FileWatcher::observers private
Definition at line 27 of file FileWatcher.hpp.
Referenced by addObserver(), notifyObservers(), and removeObserver().
wd
int FileWatcher::wd private
Definition at line 26 of file FileWatcher.hpp.
Referenced by setFileToWatch(), and ~FileWatcher().
The documentation for this class was generated from the following files:
src/Observer/FileWatcher.hpp
src/Observer/FileWatcher.cpp