PotatRaycer: Ray Class Reference
Ray Class Reference
#include <Ray.hpp>
Public Member Functions
Ray ()
~Ray ()
Ray (const Vec3 &a, const Vec3 &b)
Vec3 getOrigin () const
Vec3 getDirection () const
Vec3 point_at_parameter (float t) const
Private Attributes
Vec3 origin
Vec3 direction
Detailed Description
Definition at line 15 of file Ray.hpp.
Constructor & Destructor Documentation
Ray() [1/2]
Ray::Ray ()
Definition at line 10 of file Ray.cpp.
 {
     // Logger *logger = LoggerSingleton::getInstance();
     // std::ostringstream msg;
     // msg << "LOG: Ray created without params.";
     // logger->log(DEBUG, msg.str());
 }
~Ray()
Ray::~Ray ()
Definition at line 18 of file Ray.cpp.
 {
 }
Ray() [2/2]
Ray::Ray (const Vec3 & a, const Vec3 & b)
Definition at line 22 of file Ray.cpp.
                                      : origin(a), direction(b)
 {
     // Logger *logger = LoggerSingleton::getInstance();
     // std::ostringstream msg;
     // msg << "LOG: Ray created with these params. a = " << a << ", b = " << b << ".";
     // logger->log(INFO, msg.str());
 }
Member Function Documentation
getDirection()
Vec3 Ray::getDirection () const
Definition at line 35 of file Ray.cpp.
 {
     return direction;
 }
References direction.
Referenced by Circle::hit(), Sphere::hit(), Triangle::hit(), Plane::hit(), Texture::scatter(), Dielectric::scatter(), and Metal::scatter().
getOrigin()
Vec3 Ray::getOrigin () const
Definition at line 30 of file Ray.cpp.
 {
     return origin;
 }
References origin.
Referenced by Circle::hit(), Sphere::hit(), Triangle::hit(), and Plane::hit().
point_at_parameter()
Vec3 Ray::point_at_parameter (float t) const
Definition at line 40 of file Ray.cpp.
 {
     return origin + (t * direction); //va falloir implémenter cette op
 }
References direction, and origin.
Referenced by Circle::hit(), Sphere::hit(), Triangle::hit(), and Plane::hit().
Member Data Documentation
direction
Vec3 Ray::direction private
Definition at line 26 of file Ray.hpp.
Referenced by getDirection(), and point_at_parameter().
origin
Vec3 Ray::origin private
Definition at line 25 of file Ray.hpp.
Referenced by getOrigin(), and point_at_parameter().
The documentation for this class was generated from the following files:
src/Ray/Ray.hpp
src/Ray/Ray.cpp