PotatRaycer: Lambertian Class Reference
Lambertian Class Reference
#include <Lambertian.hpp>
Public Member Functions
Lambertian (const Vec3 &a)
~Lambertian ()
bool scatter (const Ray &r_in, const hit_record_t &rec, Vec3 &attenuation, Ray &scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> &_obj) const override final
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec, const std::vector< std::shared_ptr< IHitable >> &_obj) const
std::string getName () const override final
Public Member Functions inherited from IMaterial
virtual ~IMaterial ()=default
Private Attributes
Vec3 albedo
Detailed Description
Definition at line 13 of file Lambertian.hpp.
Constructor & Destructor Documentation
Lambertian()
Lambertian::Lambertian (const Vec3 & a)
Definition at line 11 of file Lambertian.cpp.
                                     : albedo(a)
 {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Lambertian created with a = " << a << ".";
     logger->log(INFO, msg.str());
 }
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~Lambertian()
Lambertian::~Lambertian ()
Definition at line 19 of file Lambertian.cpp.
 {
 }
Member Function Documentation
getName()
std::string Lambertian::getName () const final override virtual
Implements IMaterial.
Definition at line 100 of file Lambertian.cpp.
 {
     return "Lambertian";
 }
Referenced by hit().
hit()
bool Lambertian::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec, const std::vector< std::shared_ptr< IHitable >> & _obj) const
Definition at line 23 of file Lambertian.cpp.
{
     hit_record_t temp_rec;
     bool hit_anything = false;
     double closest_so_far = t_max;
     for(int i = 0; i < _world.size(); i++) {
         if (_world[i]->hit(r,t_min,closest_so_far,temp_rec) && _world[i]->getMaterial()->getName() != "LightTexture") {
             hit_anything = true;
             closest_so_far = temp_rec.t;
             rec = temp_rec;
         }
     }
     return hit_anything;
 }
References getName(), and hit_record_s::t.
Referenced by scatter().
scatter()
bool Lambertian::scatter (const Ray & r_in, const hit_record_t & rec, Vec3 & attenuation, Ray & scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> & _obj) const final override virtual
Implements IMaterial.
Definition at line 37 of file Lambertian.cpp.
 {
     if (!(light->getType() == "directional")) {
         Vec3 lightDir = light->calculateLightDirection(rec.p);
         float cos_theta = fabs(dot(rec.normal, lightDir));
         Vec3 shadowRayOrigin = rec.p;
         Vec3 shadowRayDirection = light->getPosition() - rec.p;
         Ray shadowRay(shadowRayOrigin, shadowRayDirection);
         hit_record_t shadowRec;
         if (hit(shadowRay, 0.001, MAXFLOAT, shadowRec, _obj)) {
             float distanceToLight = (light->getPosition() - rec.p).length();
             float attenuationFactor = 1 / (1 + distanceToLight);
             attenuation = albedo * light->getIntensity() * cos_theta * attenuationFactor;
             return false;
         }
         scattered = Ray(rec.p, rec.normal + random_in_unit_sphere());
         attenuation = albedo * light->getIntensity() * cos_theta;
         return true;
     } else {
         Vec3 lightDir = light->getNormal();
         lightDir.make_unit_vector();
         Vec3 lightPos = light->getPosition();
         float cos_theta = dot(rec.normal, lightDir);
         Vec3 pointToLight = lightPos - rec.p;
         if (dot(pointToLight, light->getNormal()) > 0 && cos_theta > 0) {
             Vec3 shadowRayOrigin = rec.p;
             Vec3 shadowRayDirection = lightDir;
             Ray shadowRay(shadowRayOrigin, shadowRayDirection);
             hit_record_t shadowRec;
             if (hit(shadowRay, 0.001, MAXFLOAT, shadowRec, _obj)) {
                 attenuation = Vec3(0, 0, 0);
                 return false;
             }
             else {
                 float lightsize = light->getSize();
                 if (lightsize > 0.0) {
                     Vec3 lightOriginToHit = rec.p - lightPos;
                     Vec3 lightNormal = light->getNormal();
                     Vec3 projectedHitToLight = lightOriginToHit - dot(lightOriginToHit, lightNormal) * lightNormal;
                     float projectedDistanceToLight = projectedHitToLight.length();
                     if (projectedDistanceToLight < lightsize) {
                         scattered = Ray(rec.p, rec.normal + random_in_unit_sphere());
                         attenuation = albedo * light->getIntensity() * cos_theta;
                         return true;
                     } else {
                         attenuation = Vec3(0, 0, 0);
                         return false;
                     }
                 } else {
                     scattered = Ray(rec.p, rec.normal + random_in_unit_sphere());
                     attenuation = albedo * light->getIntensity() * cos_theta;
                     return true;
                 }
             }
         }
         else {
             attenuation = Vec3(0, 0, 0);
             return false;
         }
     }
 }
References albedo, dot(), hit(), Vec3::length(), Vec3::make_unit_vector(), hit_record_s::normal, hit_record_s::p, and random_in_unit_sphere().
Member Data Documentation
albedo
Vec3 Lambertian::albedo private
Definition at line 21 of file Lambertian.hpp.
Referenced by scatter().
The documentation for this class was generated from the following files:
src/Materials/Lambertian/Lambertian.hpp
src/Materials/Lambertian/Lambertian.cpp