PotatRaycer: FileWatcherSingleton Class Reference
FileWatcherSingleton Class Reference
Singleton for the FileWatcher class.
#include <FileWatcherSingleton.hpp>
Public Member Functions
FileWatcherSingleton (const FileWatcherSingleton &)=delete
FileWatcherSingleton & operator= (const FileWatcherSingleton &)=delete
Static Public Member Functions
static FileWatcher * getInstance ()
Get the instance of the singleton.
static void destroyInstance ()
Private Member Functions
FileWatcherSingleton ()
Static Private Attributes
static FileWatcher * instance = nullptr
Detailed Description
Singleton for the FileWatcher class.
Definition at line 23 of file FileWatcherSingleton.hpp.
Constructor & Destructor Documentation
FileWatcherSingleton() [1/2]
FileWatcherSingleton::FileWatcherSingleton (const FileWatcherSingleton &) delete
FileWatcherSingleton() [2/2]
FileWatcherSingleton::FileWatcherSingleton () inline private
Definition at line 37 of file FileWatcherSingleton.hpp.
 {}
Member Function Documentation
destroyInstance()
void FileWatcherSingleton::destroyInstance () static
Definition at line 25 of file FileWatcherSingleton.cpp.
 {
     if (instance != nullptr) {
         delete instance;
         instance = nullptr;
     }
 }
References instance.
getInstance()
FileWatcher * FileWatcherSingleton::getInstance () static
Get the instance of the singleton.
Returns
The instance of the singleton.
Definition at line 17 of file FileWatcherSingleton.cpp.
 {
     if (instance == nullptr) {
         instance = new FileWatcher();
     }
     return instance;
 }
References instance.
Referenced by Core::generatePPM(), Compute::loop(), and main().
operator=()
FileWatcherSingleton& FileWatcherSingleton::operator= (const FileWatcherSingleton &) delete
Member Data Documentation
instance
FileWatcher * FileWatcherSingleton::instance = nullptr static private
Definition at line 36 of file FileWatcherSingleton.hpp.
Referenced by destroyInstance(), and getInstance().
The documentation for this class was generated from the following files:
src/Observer/FileWatcherSingleton.hpp
src/Observer/FileWatcherSingleton.cpp