PotatRaycer: Metal Class Reference
Metal Class Reference
Class used to create a Metal.
#include <Metal.hpp>
Public Member Functions
Metal (const Vec3 &albedo, const float f)
Construct a new Metal object.
~Metal ()
bool scatter (const Ray &r_in, const hit_record_t &rec, Vec3 &attenuation, Ray &scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> &_obj) const override final
Function to scatter the ray.
std::string getName () const override final
Function to get the name of the material.
Public Member Functions inherited from IMaterial
virtual ~IMaterial ()=default
Private Attributes
Vec3 albedo
int fuzz
Detailed Description
Class used to create a Metal.
Definition at line 23 of file Metal.hpp.
Constructor & Destructor Documentation
Metal()
Metal::Metal (const Vec3 & albedo, const float f)
Construct a new Metal object.
Parameters
albedo The albedo of the metal.
f The fuzz of the metal.
Definition at line 16 of file Metal.cpp.
                                               : albedo(albedo)
 {
     if (f < 1)
         fuzz = f;
     else
         fuzz = 1;
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Metal created with these parameters: a = " << albedo << ", f = " << f << ".";
     logger->log(INFO, msg.str());
 }
References albedo, fuzz, LoggerSingleton::getInstance(), INFO, and Logger::log().
~Metal()
Metal::~Metal ()
Definition at line 29 of file Metal.cpp.
 {
 }
Member Function Documentation
getName()
std::string Metal::getName () const final override virtual
Function to get the name of the material.
Returns
The name of the material.
Implements IMaterial.
Definition at line 41 of file Metal.cpp.
 {
     return "Metal";
 }
scatter()
bool Metal::scatter (const Ray & r_in, const hit_record_t & rec, Vec3 & attenuation, Ray & scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> & _obj) const final override virtual
Function to scatter the ray.
Parameters
r_in The ray.
rec The hit record.
attenuation The attenuation.
scattered The scattered ray.
light The light.
_obj The objects in the scene.
Returns
True if the ray has been scattered, false otherwise.
Implements IMaterial.
Definition at line 33 of file Metal.cpp.
 {
     Vec3 reflected = reflect(unit_vector(r_in.getDirection()), rec.normal);
     scattered = Ray(rec.p, reflected + fuzz * random_in_unit_sphere());
     attenuation = albedo;
     return false;
 }
References albedo, fuzz, Ray::getDirection(), random_in_unit_sphere(), reflect(), and unit_vector().
Member Data Documentation
albedo
Vec3 Metal::albedo private
Definition at line 35 of file Metal.hpp.
Referenced by Metal(), and scatter().
fuzz
int Metal::fuzz private
Definition at line 36 of file Metal.hpp.
Referenced by Metal(), and scatter().
The documentation for this class was generated from the following files:
src/Materials/Metal/Metal.hpp
src/Materials/Metal/Metal.cpp