PotatRaycer: LoggerSingleton Class Reference
LoggerSingleton Class Reference
#include <SingletonLogger.hpp>
Public Member Functions
LoggerSingleton (const LoggerSingleton &)=delete
LoggerSingleton & operator= (const LoggerSingleton &)=delete
Static Public Member Functions
static Logger * getInstance ()
static void destroyInstance ()
Private Member Functions
LoggerSingleton ()
Static Private Attributes
static Logger * instance = nullptr
Detailed Description
Definition at line 15 of file SingletonLogger.hpp.
Constructor & Destructor Documentation
LoggerSingleton() [1/2]
LoggerSingleton::LoggerSingleton () inline private
Definition at line 18 of file SingletonLogger.hpp.
 {}
LoggerSingleton() [2/2]
LoggerSingleton::LoggerSingleton (const LoggerSingleton &) delete
Member Function Documentation
destroyInstance()
void LoggerSingleton::destroyInstance () static
Definition at line 19 of file SingletonLogger.cpp.
{
     delete instance;
     instance = nullptr;
 }
References instance.
getInstance()
Logger * LoggerSingleton::getInstance () static
Definition at line 12 of file SingletonLogger.cpp.
{
     if (instance == nullptr) {
         instance = new Logger("logfile.txt");
     }
     return instance;
 }
References instance.
Referenced by AmbiantLight::AmbiantLight(), Core::assembleScene(), Camera::Camera(), Circle::Circle(), Compute::Compute(), Core::Core(), Dielectric::Dielectric(), DirectionalLight::DirectionalLight(), Core::generatePPM(), Lambertian::Lambertian(), LightTexture::LightTexture(), Compute::loop(), main(), Metal::Metal(), Parsing::parseLogger(), Parsing::parsePrimitives(), Parsing::Parsing(), Plane::Plane(), Scene::Scene(), SceneBuilder::SceneBuilder(), and Sphere::Sphere().
operator=()
LoggerSingleton& LoggerSingleton::operator= (const LoggerSingleton &) delete
Member Data Documentation
instance
Logger * LoggerSingleton::instance = nullptr static private
Definition at line 17 of file SingletonLogger.hpp.
Referenced by destroyInstance(), and getInstance().
The documentation for this class was generated from the following files:
src/Logger/SingletonLogger.hpp
src/Logger/SingletonLogger.cpp