PotatRaycer: Vec2 Class Reference
Vec2 Class Reference
Class for representing a 2D vector.
#include <Vec2.hpp>
Public Member Functions
Vec2 ()
Default constructor for Vec2.
Vec2 (float e0, float e1)
Parameterized constructor for Vec2.
Vec2 operator* (float scalar) const
Multiplies the vector by a scalar.
Vec2 operator+ (const Vec2 &other) const
Adds two Vec2 vectors.
Public Attributes
float e [2]
Array storing the x and y coordinates of the vector.
Detailed Description
Class for representing a 2D vector.
The Vec2 class provides basic operations for 2-dimensional vectors, including initialization, scaling, and addition.
Definition at line 25 of file Vec2.hpp.
Constructor & Destructor Documentation
Vec2() [1/2]
Vec2::Vec2 () inline
Default constructor for Vec2.
Initializes the vector with zero values.
Definition at line 32 of file Vec2.hpp.
 : e{0.0f, 0.0f} {}
Referenced by operator*(), and operator+().
Vec2() [2/2]
Vec2::Vec2 (float e0, float e1) inline
Parameterized constructor for Vec2.
Parameters
e0 The x-coordinate of the vector.
e1 The y-coordinate of the vector.
Definition at line 40 of file Vec2.hpp.
{
             e[0] = e0;
             e[1] = e1;
         }
References e.
Member Function Documentation
operator*()
Vec2 Vec2::operator* (float scalar) const inline
Multiplies the vector by a scalar.
Parameters
scalar The scalar value to multiply with.
Returns
Vec2 The resulting vector after multiplication.
Definition at line 51 of file Vec2.hpp.
{
             return Vec2(e[0] * scalar, e[1] * scalar);
         }
References e, and Vec2().
operator+()
Vec2 Vec2::operator+ (const Vec2 & other) const inline
Adds two Vec2 vectors.
Parameters
other The other vector to add.
Returns
Vec2 The resulting vector after addition.
Definition at line 61 of file Vec2.hpp.
{
             return Vec2(e[0] + other.e[0], e[1] + other.e[1]);
         }
References e, and Vec2().
Member Data Documentation
e
float Vec2::e[2]
Array storing the x and y coordinates of the vector.
Definition at line 65 of file Vec2.hpp.
Referenced by operator*(), operator+(), and Vec2().
The documentation for this class was generated from the following file:
src/Vec2/Vec2.hpp