PotatRaycer: SceneBuilder Class Reference
SceneBuilder Class Reference
#include <SceneBuilder.hpp>
Public Member Functions
SceneBuilder ()
~SceneBuilder ()
void createCamera (std::map< std::string, std::tuple< float, float, float >>) override final
void createLight (std::map< std::string, std::tuple< float, float, float >>) override final
void createPrimitives (std::vector< Primitive >) override final
const Scene & getScene () const override final
void createMeshFromObj (std::vector< ObjectProperties > obj)
Public Member Functions inherited from IBuilder
virtual ~IBuilder ()=default
Private Attributes
Scene scene
Detailed Description
Definition at line 16 of file SceneBuilder.hpp.
Constructor & Destructor Documentation
SceneBuilder()
SceneBuilder::SceneBuilder ()
Definition at line 29 of file SceneBuilder.cpp.
 {
     Scene();
     Logger* logger = LoggerSingleton::getInstance();
     logger->log(INFO, "SceneBuilder created.");
 }
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~SceneBuilder()
SceneBuilder::~SceneBuilder ()
Definition at line 36 of file SceneBuilder.cpp.
 {}
Member Function Documentation
createCamera()
void SceneBuilder::createCamera (std::map< std::string, std::tuple< float, float, float >> camParams) final override virtual
Implements IBuilder.
Definition at line 38 of file SceneBuilder.cpp.
 {
     Vec3 lookfrom;
     Vec3 lookat;
     Vec3 vup;
     float vfov;
     float aspect;
     float aperture;
     float focus_dist;
     try {
         lookfrom = Vec3(std::get<0>(camParams["lookfrom"]), std::get<1>(camParams["lookfrom"]), std::get<2>(camParams["lookfrom"]));
         lookat = Vec3(std::get<0>(camParams["lookat"]), std::get<1>(camParams["lookat"]), std::get<2>(camParams["lookat"]));
         vup = Vec3(std::get<0>(camParams["vup"]), std::get<1>(camParams["vup"]), std::get<2>(camParams["vup"]));
         vfov = std::get<0>(camParams["vfov"]);
         aspect = std::get<0>(camParams["aspect"]);
         aperture = std::get<0>(camParams["aperture"]);
         focus_dist = std::get<0>(camParams["focus_dist"]);
         scene.setConfigHeight(std::get<0>(camParams["height"]));
         scene.setConfigWidth(std::get<0>(camParams["width"]));
         scene.setConfigNs(std::get<0>(camParams["ns"]));
     } catch (const std::exception &e) {
         throw Exception("Camera parameters not found.", Level::MIDDLE);
     }
     Camera camera = Camera(lookfrom, lookat, vup, vfov, aspect, aperture, focus_dist);
     scene.setCamera(camera);
 }
References MIDDLE, scene, Scene::setCamera(), Scene::setConfigHeight(), Scene::setConfigNs(), and Scene::setConfigWidth().
Referenced by Core::assembleScene().
createLight()
void SceneBuilder::createLight (std::map< std::string, std::tuple< float, float, float >> lightParams) final override virtual
Implements IBuilder.
Definition at line 67 of file SceneBuilder.cpp.
 {
     Vec3 pos, normal;
     float intensity, direc, size;
     try {
         pos = Vec3(std::get<0>(lightParams.at("position")), std::get<1>(lightParams.at("position")), std::get<2>(lightParams.at("position")));
         intensity = std::get<0>(lightParams.at("intensity"));
         normal = Vec3(std::get<0>(lightParams.at("normal")),
                       std::get<1>(lightParams.at("normal")),
                       std::get<2>(lightParams.at("normal")));
         direc = std::get<0>(lightParams.at("direc"));
         size = std::get<0>(lightParams.at("size"));
     } catch (const std::exception& e) {
         throw Exception("Light parameters not found.", Level::MIDDLE);
     }
     if (direc == 0) {
         std::shared_ptr<ILight> light = std::make_shared<AmbiantLight>(pos, intensity);
         scene.setLight(light);
     } else {
         std::shared_ptr<ILight> light = std::make_shared<DirectionalLight>(pos, intensity, normal, size);
         scene.setLight(light);
     }
 }
References MIDDLE, scene, and Scene::setLight().
Referenced by Core::assembleScene().
createMeshFromObj()
void SceneBuilder::createMeshFromObj (std::vector< ObjectProperties > obj)
Definition at line 129 of file SceneBuilder.cpp.
 {
     try {
         for (const auto& obj : objects) {
             std::shared_ptr<IMaterial> material = std::make_shared<Texture>(obj.pathTexture);
             std::ifstream file(obj.pathFile);
             if (!file.is_open()) {
                 throw Exception("Failed to open file: " + obj.pathFile, Level::LOW);
             }
             std::vector<Vec3> vertices;
             std::vector<std::shared_ptr<IHitable>> triangles;
             std::string line;
             std::vector<Vec2> texCoords;
             while (std::getline(file, line)) {
                 std::stringstream ss(line);
                 std::string type;
                 ss >> type;
                 if (type == "v") {
                     float x, y, z;
                     ss >> x >> y >> z;
                     vertices.emplace_back(x, y, z);
                 } else if (type == "vt") {
                     float u, v;
                     ss >> u >> v;
                     texCoords.emplace_back(u, v);
                 } else if (type == "f") {
                     std::string vertexInfo;
                     std::vector<int> vertexIndices;
                     std::vector<int> textureIndices;
                     while (ss >> vertexInfo) {
                         size_t pos1 = vertexInfo.find('/');
                         size_t pos2 = vertexInfo.find('/', pos1 + 1);
                         int vertexIndex = std::stoi(vertexInfo.substr(0, pos1)) - 1;
                         vertexIndices.push_back(vertexIndex);
                         if (pos1 != std::string::npos && pos1 + 1 != pos2) {
                             int textureIndex = std::stoi(vertexInfo.substr(pos1 + 1, pos2 - pos1 - 1)) - 1;
                             textureIndices.push_back(textureIndex);
                         }
                     }
                     if (vertexIndices.size() >= 3) {
                         for (int i = 0; i < vertexIndices.size() - 2; i++) {
                             triangles.push_back(std::make_shared<Triangle>(
                                 vertices[vertexIndices[0]], vertices[vertexIndices[i + 1]], vertices[vertexIndices[i + 2]],
                                 texCoords[textureIndices[0]], texCoords[textureIndices[i + 1]], texCoords[textureIndices[i + 2]]
                             ));
                             triangles.back()->setMaterial(material);
                         }
                     }
                 }
             }
             Vec3 position(obj.position.x, obj.position.y, obj.position.z);
             Vec3 rotation(obj.rotation.x, obj.rotation.y, obj.rotation.z);
             Vec3 scale(obj.scale.x, obj.scale.y, obj.scale.z);
             file.close();
             Mesh mesh(triangles, position, rotation, scale);
             mesh.transformVertices();
             std::shared_ptr<IHitable> meshPtr = std::make_shared<Mesh>(mesh);
             scene.addObject(std::move(meshPtr));
         }
     } catch (const std::exception& e) {
         throw Exception("Error creating mesh objects: " + std::string(e.what()), Level::MIDDLE);
     }
 }
References Scene::addObject(), LOW, MIDDLE, scene, and Mesh::transformVertices().
Referenced by Core::assembleScene().
createPrimitives()
void SceneBuilder::createPrimitives (std::vector< Primitive > primitives) final override virtual
Implements IBuilder.
Definition at line 91 of file SceneBuilder.cpp.
 {
     try {
         for (const auto& prim : primitives) {
             Vec3 materialVec(prim.material.vec.x, prim.material.vec.y, prim.material.vec.z);
             std::shared_ptr<IMaterial> material;
             if (prim.material.type == "metal") {
                 material = std::make_shared<Metal>(materialVec, prim.material.fuzz);
             } else if (prim.material.type == "lambertian") {
                 material = std::make_shared<Lambertian>(materialVec);
             } else if (prim.material.type == "dielectric") {
                 material = std::make_shared<Dielectric>(prim.material.ref_idx);
             }
             /* Add effect */
             if (!prim.effect.type.empty() && prim.effect.type == "tint") {
                 material = std::make_shared<TintedMaterial>(material, Vec3(prim.effect.color.x, prim.effect.color.y, prim.effect.color.z));
             }
             if (prim.type == "sphere") {
                 Vec3 center(prim.points[0].x, prim.points[0].y, prim.points[0].z);
                 float radius = prim.points[1].x;
                 std::shared_ptr<IHitable> object = std::make_shared<Sphere>(center, radius);
                 object->setMaterial(material);
                 scene.addObject(std::move(object));
             } else if (prim.type == "plane") {
                 Vec3 point1(prim.points[0].x, prim.points[0].y, prim.points[0].z);
                 Vec3 point2(prim.points[1].x, prim.points[1].y, prim.points[1].z);
                 std::shared_ptr<IHitable> object = std::make_shared<Plane>(point1, point2);
                 object->setMaterial(material);
                 scene.addObject(object);
             }
         }
     } catch (const std::exception& e) {
         throw Exception("Error creating primitives: " + std::string(e.what()), Level::MIDDLE);
     }
 }
References Scene::addObject(), MIDDLE, and scene.
Referenced by Core::assembleScene().
getScene()
const Scene & SceneBuilder::getScene () const final override virtual
Implements IBuilder.
Definition at line 200 of file SceneBuilder.cpp.
 {
     return this->scene;
 }
References scene.
Referenced by Core::assembleScene().
Member Data Documentation
scene
Scene SceneBuilder::scene private
Definition at line 26 of file SceneBuilder.hpp.
Referenced by createCamera(), createLight(), createMeshFromObj(), createPrimitives(), and getScene().
The documentation for this class was generated from the following files:
src/Builder/SceneBuilder.hpp
src/Builder/SceneBuilder.cpp