PotatRaycer: Triangle Class Reference
Triangle Class Reference
#include <Triangle.hpp>
Public Member Functions
Triangle (const Vec3 &v0, const Vec3 &v1, const Vec3 &v2, const Vec2 &uv0, const Vec2 &uv1, const Vec2 &uv2)
~Triangle ()
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec) const
std::shared_ptr< IMaterial > getMaterial ()
void transform (const Vec3 &scale, const Vec3 &rotation, const Vec3 &position)
Vec3 applyTransform (const Vec3 &vertex, const Vec3 &scale, const Vec3 &rotation, const Vec3 &position)
void setMaterial (std::shared_ptr< IMaterial > m)
Private Attributes
Vec3 _v0
Vec3 _v1
Vec3 _v2
Vec2 _uv0
Vec2 _uv1
Vec2 _uv2
std::shared_ptr< IMaterial > _mat_ptr
Vec3 _pos
Detailed Description
Definition at line 13 of file Triangle.hpp.
Constructor & Destructor Documentation
Triangle()
Triangle::Triangle (const Vec3 & v0, const Vec3 & v1, const Vec3 & v2, const Vec2 & uv0, const Vec2 & uv1, const Vec2 & uv2)
Definition at line 10 of file Triangle.cpp.
 : _v0(v0), _v1(v1), _v2(v2), _uv0(uv0), _uv1(uv1), _uv2(uv2) {}
~Triangle()
Triangle::~Triangle ()
Definition at line 13 of file Triangle.cpp.
 {}
Member Function Documentation
applyTransform()
Vec3 Triangle::applyTransform (const Vec3 & vertex, const Vec3 & scale, const Vec3 & rotation, const Vec3 & position)
Definition at line 95 of file Triangle.cpp.
{
     Vec3 scaled = scaleVertex(vertex, scale);
     Vec3 rotated = rotateVertex(scaled, rotation);
     return translateVertex(rotated, position);
 }
References rotateVertex(), scaleVertex(), and translateVertex().
Referenced by transform().
getMaterial()
std::shared_ptr<IMaterial> Triangle::getMaterial () inline virtual
Implements IHitable.
Definition at line 18 of file Triangle.hpp.
 { return _mat_ptr; }
References _mat_ptr.
hit()
bool Triangle::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec) const virtual
Implements IHitable.
Definition at line 15 of file Triangle.cpp.
 {
     Vec3 edge1 = _v1 - _v0;
     Vec3 edge2 = _v2 - _v0;
     Vec3 h = cross(ray.getDirection(), edge2);
     float a = dot(edge1, h);
     if (a > -0.0001f && a < 0.0001f)
         return false;
     float f = 1.0 / a;
     Vec3 s = ray.getOrigin() - _v0;
     float u = f * dot(s, h);
     if (u < 0.0 || u > 1.0)
         return false;
     Vec3 q = cross(s, edge1);
     float v = f * dot(ray.getDirection(), q);
     if (v < 0.0 || u + v > 1.0)
         return false;
     float t = f * dot(edge2, q);
     if (t > t_min && t < t_max) {
         float w = 1.0f - u - v; // Coordonnée barycentrique pour le troisième sommet
         rec.uv = _uv0 * w + _uv1 * u + _uv2 * v; // Interpolation des coordonnées UV
         rec.t = t;
         rec.p = ray.point_at_parameter(t);
         rec.normal = cross(edge1, edge2).normalize();
         rec.mat_ptr = _mat_ptr;
         return true;
     }
     return false;
 }
References _mat_ptr, _uv0, _uv1, _uv2, _v0, _v1, _v2, cross(), dot(), Ray::getDirection(), Ray::getOrigin(), hit_record_s::mat_ptr, hit_record_s::normal, Vec3::normalize(), hit_record_s::p, Ray::point_at_parameter(), hit_record_s::t, and hit_record_s::uv.
setMaterial()
void Triangle::setMaterial (std::shared_ptr< IMaterial > m) inline virtual
Implements IHitable.
Definition at line 21 of file Triangle.hpp.
 { _mat_ptr = m; };
References _mat_ptr.
transform()
void Triangle::transform (const Vec3 & scale, const Vec3 & rotation, const Vec3 & position)
Definition at line 51 of file Triangle.cpp.
 {
     _v0 = applyTransform(_v0, scale, rotation, position);
     _v1 = applyTransform(_v1, scale, rotation, position);
     _v2 = applyTransform(_v2, scale, rotation, position);
 }
References _v0, _v1, _v2, and applyTransform().
Member Data Documentation
_mat_ptr
std::shared_ptr<IMaterial> Triangle::_mat_ptr private
Definition at line 25 of file Triangle.hpp.
Referenced by getMaterial(), hit(), and setMaterial().
_pos
Vec3 Triangle::_pos private
Definition at line 26 of file Triangle.hpp.
_uv0
Vec2 Triangle::_uv0 private
Definition at line 24 of file Triangle.hpp.
Referenced by hit().
_uv1
Vec2 Triangle::_uv1 private
Definition at line 24 of file Triangle.hpp.
Referenced by hit().
_uv2
Vec2 Triangle::_uv2 private
Definition at line 24 of file Triangle.hpp.
Referenced by hit().
_v0
Vec3 Triangle::_v0 private
Definition at line 23 of file Triangle.hpp.
Referenced by hit(), and transform().
_v1
Vec3 Triangle::_v1 private
Definition at line 23 of file Triangle.hpp.
Referenced by hit(), and transform().
_v2
Vec3 Triangle::_v2 private
Definition at line 23 of file Triangle.hpp.
Referenced by hit(), and transform().
The documentation for this class was generated from the following files:
src/Primitives/Triangle/Triangle.hpp
src/Primitives/Triangle/Triangle.cpp