PotatRaycer: Dielectric Class Reference
Dielectric Class Reference
Class used to create the Dielectric.
#include <Dielectric.hpp>
Public Member Functions
Dielectric (float ri)
Construct a new Dielectric object.
~Dielectric ()
bool scatter (const Ray &r_in, const hit_record_t &rec, Vec3 &attenuation, Ray &scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> &_obj) const override final
Function to scatter the ray.
std::string getName () const override final
Function to get the name of the material.
Public Member Functions inherited from IMaterial
virtual ~IMaterial ()=default
Private Attributes
float ref_idx
Detailed Description
Class used to create the Dielectric.
Definition at line 25 of file Dielectric.hpp.
Constructor & Destructor Documentation
Dielectric()
Dielectric::Dielectric (float ri)
Construct a new Dielectric object.
Parameters
ri The refraction index.
Definition at line 16 of file Dielectric.cpp.
                                : ref_idx(ri)
 {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Dielectric created with this parameter: ri = " << ri << ".";
     logger->log(INFO, msg.str());
 }
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~Dielectric()
Dielectric::~Dielectric ()
Definition at line 24 of file Dielectric.cpp.
 {
 }
Member Function Documentation
getName()
std::string Dielectric::getName () const final override virtual
Function to get the name of the material.
Returns
The name of the material.
Implements IMaterial.
Definition at line 57 of file Dielectric.cpp.
 {
     return "Dielectric";
 }
scatter()
bool Dielectric::scatter (const Ray & r_in, const hit_record_t & rec, Vec3 & attenuation, Ray & scattered, std::shared_ptr< ILight > light, const std::vector< std::shared_ptr< IHitable >> & _obj) const final override virtual
Function to scatter the ray.
Parameters
r_in The ray.
rec The hit record.
attenuation The attenuation.
scattered The scattered ray.
light The light.
_obj The objects in the scene.
Returns
True if the ray has been scattered, false otherwise.
Implements IMaterial.
Definition at line 27 of file Dielectric.cpp.
 {
     Vec3 outward_normal;
     Vec3 reflected = reflect(r_in.getDirection(), rec.normal);
     float ni_over_nt;
     attenuation = Vec3(1.0, 1.0, 1.0);
     Vec3 refracted;
     float reflect_prob;
     float cosine;
     if (dot(r_in.getDirection(), rec.normal) > 0) {
         outward_normal = -rec.normal;
         ni_over_nt = ref_idx;
         cosine =  dot(r_in.getDirection(), rec.normal) / r_in.getDirection().length();
         cosine = sqrt(1 - ref_idx * ref_idx * (1 - cosine * cosine));
     } else {
         outward_normal = rec.normal;
         ni_over_nt = 1.0 / ref_idx;
         cosine = -dot(r_in.getDirection(), rec.normal) / r_in.getDirection().length();
     }
     if (refract(r_in.getDirection(), outward_normal, ni_over_nt, refracted))
         reflect_prob = schlick(cosine, ref_idx);
     else
         reflect_prob = 1.0;
     if (drand48() < reflect_prob)
         scattered = Ray(rec.p, reflected);
     else
         scattered = Ray(rec.p, refracted);
     return true;
 }
References dot(), Ray::getDirection(), Vec3::length(), ref_idx, reflect(), refract(), and schlick().
Member Data Documentation
ref_idx
float Dielectric::ref_idx private
Definition at line 37 of file Dielectric.hpp.
Referenced by scatter().
The documentation for this class was generated from the following files:
src/Materials/Dielectric/Dielectric.hpp
src/Materials/Dielectric/Dielectric.cpp