PotatRaycer: Plane Class Reference
Plane Class Reference
#include <Plane.hpp>
Public Member Functions
Plane (Vec3 p, Vec3 n)
~Plane ()
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec) const override final
void setMaterial (std::shared_ptr< IMaterial > m)
std::shared_ptr< IMaterial > getMaterial ()
Private Attributes
Vec3 point
Vec3 normal
std::shared_ptr< IMaterial > mat_ptr
Detailed Description
Definition at line 16 of file Plane.hpp.
Constructor & Destructor Documentation
Plane()
Plane::Plane (Vec3 p, Vec3 n)
Definition at line 11 of file Plane.cpp.
                            : point(p), normal(n)
 {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Plane created with these params. p = " << p << ", n = " << n << ".";
     logger->log(INFO, msg.str());
 };
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~Plane()
Plane::~Plane ()
Definition at line 19 of file Plane.cpp.
 {
 }
Member Function Documentation
getMaterial()
std::shared_ptr< IMaterial > Plane::getMaterial () virtual
Implements IHitable.
Definition at line 28 of file Plane.cpp.
 {
     return mat_ptr;
 }
References mat_ptr.
hit()
bool Plane::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec) const final override virtual
Implements IHitable.
Definition at line 33 of file Plane.cpp.
 {
     float denom = dot(normal, r.getDirection());
     if (fabs(denom) > 1e-6) {
         Vec3 p0l0 = point - r.getOrigin();
         float t = dot(p0l0, normal) / denom;
         if (t < t_max && t > t_min) {
             rec.t = t;
             rec.p = r.point_at_parameter(rec.t);
             rec.normal = normal;
             rec.mat_ptr = mat_ptr;
             return true;
         }
     }
     return false;
 }
References dot(), Ray::getDirection(), Ray::getOrigin(), mat_ptr, hit_record_s::mat_ptr, normal, hit_record_s::normal, hit_record_s::p, point, Ray::point_at_parameter(), and hit_record_s::t.
setMaterial()
void Plane::setMaterial (std::shared_ptr< IMaterial > m) virtual
Implements IHitable.
Definition at line 23 of file Plane.cpp.
 {
     mat_ptr = std::move(m);
 }
References mat_ptr.
Member Data Documentation
mat_ptr
std::shared_ptr<IMaterial> Plane::mat_ptr private
Definition at line 26 of file Plane.hpp.
Referenced by getMaterial(), hit(), and setMaterial().
normal
Vec3 Plane::normal private
Definition at line 25 of file Plane.hpp.
Referenced by hit().
point
Vec3 Plane::point private
Definition at line 24 of file Plane.hpp.
Referenced by hit().
The documentation for this class was generated from the following files:
src/Primitives/Plane/Plane.hpp
src/Primitives/Plane/Plane.cpp