PotatRaycer: Exception Class Reference
Exception Class Reference
Class used to create the Exception.
#include <Exception.hpp>
Public Member Functions
Exception (const std::string &msg, Level lvl=Level::NONE)
Construct a new Exception object.
const char * what () const noexcept
Get the message of the exception.
Level getLevel () const
Get the level of the exception.
Private Attributes
std::string message
Level lvl
Detailed Description
Class used to create the Exception.
Definition at line 36 of file Exception.hpp.
Constructor & Destructor Documentation
Exception()
Exception::Exception (const std::string & msg, Level lvl = Level::NONE) inline
Construct a new Exception object.
Parameters
msg The message of the exception.
lvl The level of the exception.
Definition at line 43 of file Exception.hpp.
 : message(msg), lvl(lvl) {}
Member Function Documentation
getLevel()
Level Exception::getLevel () const inline
Get the level of the exception.
Returns
The level of the exception.
Definition at line 58 of file Exception.hpp.
{
             return this->lvl;
         }
References lvl.
Referenced by main().
what()
const char* Exception::what () const inline noexcept
Get the message of the exception.
Returns
The message of the exception.
Definition at line 49 of file Exception.hpp.
         {
             return message.c_str();
         }
References message.
Referenced by Core::assembleScene(), Compute::Compute(), Core::generatePPM(), and main().
Member Data Documentation
lvl
Level Exception::lvl private
Definition at line 63 of file Exception.hpp.
Referenced by getLevel().
message
std::string Exception::message private
Definition at line 62 of file Exception.hpp.
Referenced by what().
The documentation for this class was generated from the following file:
src/Exceptions/Exception.hpp