PotatRaycer: Compute Class Reference
Compute Class Reference
Class used to compute the image.
#include <Computing.hpp>
Public Member Functions
Compute (Scene scene)
~Compute ()
void loop (Scene scene)
Loop function to compute the image.
Vec3 colorloop (const Ray &r, const std::vector< std::shared_ptr< IHitable >> &_objects, std::shared_ptr< ILight > _light)
Function to compute the color of the pixel.
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec) const
Function to check if the object has been hit by the Ray.
void colorThread (int x, int end_x, int y, int i, std::map< int, std::string > &maMap, sf::Image &image)
Function to compute the color of the pixel.
void reset () override final
Public Member Functions inherited from IObserver
virtual ~IObserver ()
Private Attributes
std::vector< std::shared_ptr< IHitable > > _world
std::shared_ptr< ILight > _light
Camera _cam
int _width
int _height
bool _change = false
int _ns
Detailed Description
Class used to compute the image.
Definition at line 28 of file Computing.hpp.
Constructor & Destructor Documentation
Compute()
Compute::Compute (Scene scene)
Definition at line 23 of file Computing.cpp.
 {
     Logger* logger = LoggerSingleton::getInstance();
     logger->log(INFO, "Compute created.");
     try {
         _world = scene.getObjects();
         _light = scene.getLight();
         _cam = scene.getCamera();
         _width = scene.getWidth();
         _height = scene.getHeight();
         _ns = scene.getNs();
         if (_light->getType() == "directional") {
             std::shared_ptr<IMaterial> material = std::make_shared<LightTexture>(_light->getIntensity());
             std::shared_ptr<IHitable> object = std::make_shared<Circle>(_light->getPosition(), _light->getNormal(), _light->getSize());
             object->setMaterial(material);
             _world.push_back(object);
         }
     } catch (const Exception& e) {
         throw Exception("An error occurred during scene assembly: " + std::string(e.what()), Level::HIGH);
     }
 }
References _cam, _height, _light, _ns, _width, _world, Scene::getCamera(), Scene::getHeight(), LoggerSingleton::getInstance(), Scene::getLight(), Scene::getNs(), Scene::getObjects(), Scene::getWidth(), HIGH, INFO, Logger::log(), and Exception::what().
~Compute()
Compute::~Compute ()
Definition at line 46 of file Computing.cpp.
 {}
Member Function Documentation
colorloop()
Vec3 Compute::colorloop (const Ray & r, const std::vector< std::shared_ptr< IHitable >> & _objects, std::shared_ptr< ILight > _light)
Function to compute the color of the pixel.
Parameters
r The ray.
_objects The objects in the scene.
_light The light in the scene.
Returns
The color of the pixel.
Definition at line 153 of file Computing.cpp.
 {
     int depth = 0;
     hit_record_t rec;
     Ray scattered, temp_r = r;
     Vec3 attenuation, temp;
     if (hit(temp_r, 0.001, MAXFLOAT, rec)) {
         bool cond = false;
         cond = rec.mat_ptr->scatter(temp_r, rec, attenuation, scattered, _light, _world);
         depth++;
         temp = attenuation;
         if (!(hit(temp_r, 0.001, MAXFLOAT, rec))) {
             if (cond)
                 return temp;
             else
                 return Vec3(0.0, 0.0, 0.0);
         }
         if (cond)
             return temp;
         temp_r = scattered;
         while (depth < 50) {
             cond = rec.mat_ptr->scatter(temp_r, rec, attenuation, scattered, _light, _world);
             depth++;
             temp *= attenuation;
             if (!(hit(temp_r, 0.001, MAXFLOAT, rec))) {
                 if (cond)
                     return temp;
                 else
                     return Vec3(0.0, 0.0, 0.0);
             }
             if (cond)
                 return temp;
             temp_r = scattered;
         }
         return temp;
     } else {
         return Vec3(0, 0, 0);
     }
 }
References _light, _world, and hit().
Referenced by colorThread().
colorThread()
void Compute::colorThread (int x, int end_x, int y, int i, std::map< int, std::string > & maMap, sf::Image & image)
Function to compute the color of the pixel.
Parameters
x The x position of the pixel.
end_x The end x position of the pixel.
y The y position of the pixel.
i The number of the thread.
maMap The map of the colors.
image The SFML image to render in real time.
Definition at line 64 of file Computing.cpp.
 {
     std::string str;
     while (x < end_x)
     {
         Vec3 col(0, 0, 0);
         for (int s = 0; s < _ns; s++) {
             float u = float(x + drand48()) / float(_width);
             float v = float(y + drand48()) / float(_height);
             Ray r = _cam.get_Ray(u, v);
             col += colorloop(r, _world, _light);
         }
         col /= float(_ns);
         col = Vec3(sqrt(col.r()), sqrt(col.g()), sqrt(col.b()));
         int ir = int(255.99 * col[0]);
         int ig = int(255.99 * col[1]);
         int ib = int(255.99 * col[2]);
         str.append(std::to_string(ir) + " " + std::to_string(ig) + " " + std::to_string(ib) + "\n");
         sf::Color color(ir, ig, ib);
         image.setPixel(x, _height - y - 1, color);
         x++;
     }
     maMap[i] = str;
 }
References _cam, _height, _light, _ns, _width, _world, Vec3::b(), colorloop(), Vec3::g(), Camera::get_Ray(), and Vec3::r().
Referenced by loop().
hit()
bool Compute::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec) const
Function to check if the object has been hit by the Ray.
Parameters
r The ray.
t_min The minimum value of the distance between elements.
t_max The maximum value of the distance between elements.
rec The hit record (all the elements).
Returns
True if the object has been hit, false otherwise.
Definition at line 48 of file Computing.cpp.
 {
     hit_record_t temp_rec;
     bool hit_anything = false;
     double closest_so_far = t_max;
     for(int i = 0; i < _world.size(); i++) {
         if (_world[i]->hit(r,t_min,closest_so_far,temp_rec)) {
             hit_anything = true;
             closest_so_far = temp_rec.t;
             rec = temp_rec;
         }
     }
     return hit_anything;
 }
References _world.
Referenced by colorloop().
loop()
void Compute::loop (Scene scene)
Loop function to compute the image.
Parameters
scene The scene to compute.
This function iniate all the calcul to compute the image of the scene.
Definition at line 91 of file Computing.cpp.
 {
     FileWatcher *watcher = FileWatcherSingleton::getInstance();
     std::map<int, std::string> maMap;
     int num_threads = std::thread::hardware_concurrency();
     std::vector<std::thread> threads;
     std::ofstream outFile("image.ppm");
     watcher->addObserver(this);
     sf::RenderWindow window(sf::VideoMode(_width, _height), "POTATX");
     sf::Image image;
     image.create(_width, _height, sf::Color::Black);
     Logger* logger = LoggerSingleton::getInstance();
     outFile << "P3\n" << _width << " " << _height << "\n255\n";
     for (int y = _height - 1; y >= 0; y--) {
         int x = 0, end_x = _width / num_threads, end;
         for (int i = 0; i < num_threads; i++) {
             end = end_x * (i + 1);
             if (i == num_threads - 1) end = _width;
             threads.emplace_back([this, x, end, y, i, &maMap, &image](){
                 this->colorThread(x, end, y, i, maMap, image);
             });
             x += end_x;
         }
         for (auto& t : threads) {
             if (t.joinable())
                 t.join();
         }
         watcher->startWatching();
         if (_change == true) {
             _change = false;
             throw ObserverException("A modification has be detected generation will restart in 5 second", Level::NONE);
         }
         for (const auto& pair : maMap) {
             outFile << pair.second;
         }
         sf::Texture texture;
         texture.loadFromImage(image);
         sf::Sprite sprite;
         sprite.setTexture(texture);
         window.clear();
         window.draw(sprite);
         window.display();
     }
     while (window.isOpen()) {
         sf::Event event;
         while (window.pollEvent(event)) {
             if (event.type == sf::Event::Closed)
                 window.close();
         }
     }
     outFile.close();
     logger->log(DEBUG, "End of loop.");
 }
References _change, _height, _width, FileWatcher::addObserver(), colorThread(), DEBUG, LoggerSingleton::getInstance(), FileWatcherSingleton::getInstance(), Logger::log(), NONE, and FileWatcher::startWatching().
Referenced by Core::generatePPM().
reset()
void Compute::reset () final override virtual
Note
This function allow the code to reset the generation when there is a modification in the configuration file.
Implements IObserver.
Definition at line 148 of file Computing.cpp.
 {
     _change = true;
 }
References _change.
Member Data Documentation
_cam
Camera Compute::_cam private
Definition at line 74 of file Computing.hpp.
Referenced by colorThread(), and Compute().
_change
bool Compute::_change = false private
Definition at line 77 of file Computing.hpp.
Referenced by loop(), and reset().
_height
int Compute::_height private
Definition at line 76 of file Computing.hpp.
Referenced by colorThread(), Compute(), and loop().
_light
std::shared_ptr<ILight> Compute::_light private
Definition at line 73 of file Computing.hpp.
Referenced by colorloop(), colorThread(), and Compute().
_ns
int Compute::_ns private
Definition at line 78 of file Computing.hpp.
Referenced by colorThread(), and Compute().
_width
int Compute::_width private
Definition at line 75 of file Computing.hpp.
Referenced by colorThread(), Compute(), and loop().
_world
std::vector<std::shared_ptr<IHitable> > Compute::_world private
Definition at line 72 of file Computing.hpp.
Referenced by colorloop(), colorThread(), Compute(), and hit().
The documentation for this class was generated from the following files:
src/Computing/Computing.hpp
src/Computing/Computing.cpp