PotatRaycer: Scene Class Reference
Scene Class Reference
Class for representing a scene in the ray tracing application.
#include <Scene.hpp>
Public Member Functions
Scene ()
Default constructor for Scene.
~Scene ()
Destructor for Scene.
void setLight (std::shared_ptr< ILight > l)
Set the light for the scene.
void setCamera (Camera c)
Set the camera for the scene.
void addObject (std::shared_ptr< IHitable > obj)
Add an object to the scene.
void setConfigHeight (float height)
Set the configuration height of the scene.
void setConfigWidth (float width)
Set the configuration width of the scene.
void setConfigNs (float ns)
Set the configuration Ns value of the scene.
const std::vector< std::shared_ptr< IHitable > > & getObjects (void) const
Get the objects in the scene.
const std::shared_ptr< ILight > & getLight (void) const
Get the light in the scene.
const Camera & getCamera (void) const
Get the camera in the scene.
const float & getHeight (void) const
Get the configuration height of the scene.
const float & getWidth (void) const
Get the configuration width of the scene.
const float & getNs (void) const
Get the configuration Ns value of the scene.
Private Attributes
std::shared_ptr< ILight > light
Shared pointer to the light in the scene.
Camera camera
The camera of the scene.
std::vector< std::shared_ptr< IHitable > > objects
Vector of shared pointers to the objects in the scene.
float height
Configuration height of the scene.
float width
Configuration width of the scene.
float ns
Configuration Ns value of the scene.
Detailed Description
Class for representing a scene in the ray tracing application.
The Scene class encapsulates the components of a 3D scene, including lighting, camera, and objects. It provides methods to set up the scene and retrieve its components.
Definition at line 31 of file Scene.hpp.
Constructor & Destructor Documentation
Scene()
Scene::Scene ()
Default constructor for Scene.
Initializes an empty scene with no light, camera, or objects.
Definition at line 16 of file Scene.cpp.
 {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Scene created.";
     logger->log(INFO, msg.str());
 }
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~Scene()
Scene::~Scene ()
Destructor for Scene.
Cleans up the resources used by the scene.
Definition at line 24 of file Scene.cpp.
 {
     this->objects.clear();
 }
References objects.
Member Function Documentation
addObject()
void Scene::addObject (std::shared_ptr< IHitable > obj)
Add an object to the scene.
Parameters
obj A shared pointer to an IHitable object representing the object to be added.
Definition at line 39 of file Scene.cpp.
 {
     objects.push_back(obj);
 }
References objects.
Referenced by SceneBuilder::createMeshFromObj(), and SceneBuilder::createPrimitives().
getCamera()
const Camera & Scene::getCamera (void) const
Get the camera in the scene.
Returns
A constant reference to a Camera object.
Definition at line 67 of file Scene.cpp.
 {
     return this->camera;
 }
References camera.
Referenced by Compute::Compute().
getHeight()
const float & Scene::getHeight (void) const
Get the configuration height of the scene.
Returns
A constant reference to the height value.
Definition at line 72 of file Scene.cpp.
 {
     return this->height;
 }
References height.
Referenced by Compute::Compute().
getLight()
const std::shared_ptr< ILight > & Scene::getLight (void) const
Get the light in the scene.
Returns
A constant reference to a shared pointer to an ILight object.
Definition at line 62 of file Scene.cpp.
 {
     return this->light;
 }
References light.
Referenced by Compute::Compute().
getNs()
const float & Scene::getNs (void) const
Get the configuration Ns value of the scene.
Returns
A constant reference to the Ns value.
Definition at line 81 of file Scene.cpp.
 {
     return this->ns;
 }
References ns.
Referenced by Compute::Compute().
getObjects()
const std::vector< std::shared_ptr< IHitable > > & Scene::getObjects (void) const
Get the objects in the scene.
Returns
A constant reference to a vector of shared pointers to IHitable objects.
Definition at line 57 of file Scene.cpp.
 {
     return objects;
 }
References objects.
Referenced by Compute::Compute().
getWidth()
const float & Scene::getWidth (void) const
Get the configuration width of the scene.
Returns
A constant reference to the width value.
Definition at line 76 of file Scene.cpp.
 {
     return this->width;
 }
References width.
Referenced by Compute::Compute().
setCamera()
void Scene::setCamera (Camera c)
Set the camera for the scene.
Parameters
c A Camera object representing the scene's camera.
Definition at line 34 of file Scene.cpp.
 {
     this->camera = c;
 }
References camera.
Referenced by SceneBuilder::createCamera().
setConfigHeight()
void Scene::setConfigHeight (float height)
Set the configuration height of the scene.
Parameters
height The height of the scene configuration.
Definition at line 44 of file Scene.cpp.
 {
     this->height = height;
 }
References height.
Referenced by SceneBuilder::createCamera().
setConfigNs()
void Scene::setConfigNs (float ns)
Set the configuration Ns value of the scene.
Parameters
ns The Ns value of the scene configuration.
Definition at line 52 of file Scene.cpp.
 {
     this->ns = ns;
 }
References ns.
Referenced by SceneBuilder::createCamera().
setConfigWidth()
void Scene::setConfigWidth (float width)
Set the configuration width of the scene.
Parameters
width The width of the scene configuration.
Definition at line 48 of file Scene.cpp.
 {
     this->width = width;
 }
References width.
Referenced by SceneBuilder::createCamera().
setLight()
void Scene::setLight (std::shared_ptr< ILight > l)
Set the light for the scene.
Parameters
l A shared pointer to an ILight object representing the scene's light.
Definition at line 29 of file Scene.cpp.
 {
     this->light = l;
 }
References light.
Referenced by SceneBuilder::createLight().
Member Data Documentation
camera
Camera Scene::camera private
The camera of the scene.
Definition at line 133 of file Scene.hpp.
Referenced by getCamera(), and setCamera().
height
float Scene::height private
Configuration height of the scene.
Definition at line 135 of file Scene.hpp.
Referenced by getHeight(), and setConfigHeight().
light
std::shared_ptr<ILight> Scene::light private
Shared pointer to the light in the scene.
Definition at line 132 of file Scene.hpp.
Referenced by getLight(), and setLight().
ns
float Scene::ns private
Configuration Ns value of the scene.
Definition at line 137 of file Scene.hpp.
Referenced by getNs(), and setConfigNs().
objects
std::vector<std::shared_ptr<IHitable> > Scene::objects private
Vector of shared pointers to the objects in the scene.
Definition at line 134 of file Scene.hpp.
Referenced by addObject(), getObjects(), and ~Scene().
width
float Scene::width private
Configuration width of the scene.
Definition at line 136 of file Scene.hpp.
Referenced by getWidth(), and setConfigWidth().
The documentation for this class was generated from the following files:
src/Scene/Scene.hpp
src/Scene/Scene.cpp