PotatRaycer: Circle Class Reference
Circle Class Reference
Class for handling circles.
#include <Circle.hpp>
Public Member Functions
Circle (Vec3 pos, Vec3 normal, float r)
~Circle ()
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec) const
Determine if a ray hits the object.
void setMaterial (std::shared_ptr< IMaterial > m)
Set the material of the object.
std::shared_ptr< IMaterial > getMaterial ()
Get the material of the object.
Public Member Functions inherited from IHitable
virtual ~IHitable ()=default
Virtual destructor for IHitable.
Private Attributes
Vec3 position
Vec3 normal
float radius
std::shared_ptr< IMaterial > mat_ptr
Detailed Description
Class for handling circles.
Definition at line 27 of file Circle.hpp.
Constructor & Destructor Documentation
Circle()
Circle::Circle (Vec3 pos, Vec3 normal, float r)
Definition at line 16 of file Circle.cpp.
                                            : position(pos), normal(norm), radius(r) {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Circle created with these params. pos = " << pos << ", normal = " << norm << ", r = " << r << ".";
     logger->log(INFO, msg.str());
 }
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~Circle()
Circle::~Circle ()
Definition at line 23 of file Circle.cpp.
 {}
Member Function Documentation
getMaterial()
std::shared_ptr< IMaterial > Circle::getMaterial () virtual
Get the material of the object.
This method retrieves the material of the object.
Returns
A shared pointer to the material of the object.
Implements IHitable.
Definition at line 29 of file Circle.cpp.
{
     return mat_ptr;
 }
References mat_ptr.
hit()
bool Circle::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec) const virtual
Determine if a ray hits the object.
This method checks if a given ray intersects with the object within a specified range. If an intersection occurs, it populates the hit record with details about the intersection.
Parameters
r The ray to check for intersection.
t_min The minimum value of the parameter t to consider.
t_max The maximum value of the parameter t to consider.
rec The hit record to populate with intersection details.
Returns
True if the ray intersects the object, false otherwise.
Implements IHitable.
Definition at line 33 of file Circle.cpp.
{
     // Vérifier si le rayon intersecte le plan du cercle
     float denom = dot(normal, r.getDirection());
     if (fabs(denom) < 1e-6) // Rayon parallèle au plan
         return false;
     float t = dot(position - r.getOrigin(), normal) / denom;
     if (t < t_min || t > t_max)
         return false;
     Vec3 hit_point = r.point_at_parameter(t);
     float distance_squared = (hit_point - position).length_squared();
     if (distance_squared > radius * radius)
         return false;
     rec.t = t;
     rec.p = hit_point;
     rec.normal = normal;
     rec.mat_ptr = mat_ptr;
     return true;
 }
References dot(), Ray::getDirection(), Ray::getOrigin(), mat_ptr, normal, Ray::point_at_parameter(), position, and radius.
setMaterial()
void Circle::setMaterial (std::shared_ptr< IMaterial > m) virtual
Set the material of the object.
This method sets the material of the object to the provided material.
Parameters
m A shared pointer to the material to set.
Implements IHitable.
Definition at line 25 of file Circle.cpp.
{
     mat_ptr = std::move(m);
 }
References mat_ptr.
Member Data Documentation
mat_ptr
std::shared_ptr<IMaterial> Circle::mat_ptr private
Definition at line 39 of file Circle.hpp.
Referenced by getMaterial(), hit(), and setMaterial().
normal
Vec3 Circle::normal private
Definition at line 37 of file Circle.hpp.
Referenced by hit().
position
Vec3 Circle::position private
Definition at line 36 of file Circle.hpp.
Referenced by hit().
radius
float Circle::radius private
Definition at line 38 of file Circle.hpp.
Referenced by hit().
The documentation for this class was generated from the following files:
src/Primitives/Circle/Circle.hpp
src/Primitives/Circle/Circle.cpp