PotatRaycer: Sphere Class Reference
Sphere Class Reference
#include <Sphere.hpp>
Public Member Functions
Sphere (Vec3 cen, float r, std::unique_ptr< IMaterial > m)
~Sphere ()
bool hit (const Ray &r, float t_min, float t_max, hit_record_t &rec) const
Private Attributes
Vec3 center
float radius
std::unique_ptr< IMaterial > mat_ptr
Detailed Description
Definition at line 16 of file Sphere.hpp.
Constructor & Destructor Documentation
Sphere()
Sphere::Sphere (Vec3 cen, float r, std::unique_ptr< IMaterial > m)
Definition at line 11 of file Sphere.cpp.
                                                             : center(cen), radius(r), mat_ptr(std::move(m))
 {
     Logger *logger = LoggerSingleton::getInstance();
     std::ostringstream msg;
     msg << "LOG: Sphere created with these params. cen = " << cen << ", r = " << r << ", and material (find a way to print it).";
     logger->log(INFO, msg.str());
 }
References LoggerSingleton::getInstance(), INFO, and Logger::log().
~Sphere()
Sphere::~Sphere ()
Definition at line 19 of file Sphere.cpp.
 {}
Member Function Documentation
hit()
bool Sphere::hit (const Ray & r, float t_min, float t_max, hit_record_t & rec) const virtual
Implements IHitable.
Definition at line 21 of file Sphere.cpp.
 {
     Vec3 oc = r.origin() - center;
     float a = dot(r.direction(), r.direction());
     float b = dot(oc, r.direction());
     float c = dot(oc, oc) - radius * radius;
     float discriminant = b * b - a * c;
     if (discriminant > 0) {
         float temp = (-b - sqrt(discriminant)) / a;
         if (temp < t_max && temp > t_min) {
             rec.t = temp;
             rec.p = r.point_at_parameter(rec.t);
             rec.normal = (rec.p - center) / radius;
             rec.mat_ptr = mat_ptr.get();
             return true;
         }
         temp = (-b + sqrt(discriminant)) / a;
         if (temp < t_max && temp > t_min) {
             rec.t = temp;
             rec.p = r.point_at_parameter(rec.t);
             rec.normal = (rec.p - center) / radius;
             rec.mat_ptr = mat_ptr.get();
             return true;
         }
     }
     return false;
 }
References center, Ray::direction(), dot(), mat_ptr, hit_record_s::mat_ptr, hit_record_s::normal, Ray::origin(), hit_record_s::p, Ray::point_at_parameter(), radius, and hit_record_s::t.
Member Data Documentation
center
Vec3 Sphere::center private
Definition at line 22 of file Sphere.hpp.
Referenced by hit().
mat_ptr
std::unique_ptr<IMaterial> Sphere::mat_ptr private
Definition at line 24 of file Sphere.hpp.
Referenced by hit().
radius
float Sphere::radius private
Definition at line 23 of file Sphere.hpp.
Referenced by hit().
The documentation for this class was generated from the following files:
src/Primitives/Sphere/Sphere.hpp
src/Primitives/Sphere/Sphere.cpp