PotatRaycer: Core Class Reference
Core Class Reference
Class used to assemble the scene and generate the PPM file.
#include <Core.hpp>
Public Member Functions
Core ()
~Core ()
void assembleScene (const std::string &filename)
Function to assemble the scene.
void generatePPM ()
Function to generate the PPM file.
const Scene & getScene () const
Function to get the scene.
Private Attributes
Scene scene
Detailed Description
Class used to assemble the scene and generate the PPM file.
Definition at line 26 of file Core.hpp.
Constructor & Destructor Documentation
Core()
Core::Core ()
Definition at line 21 of file Core.cpp.
 {
     scene = Scene();
     Logger* logger = LoggerSingleton::getInstance();
     logger->log(INFO, "Core Created.");
 }
References LoggerSingleton::getInstance(), INFO, Logger::log(), and scene.
~Core()
Core::~Core ()
Definition at line 28 of file Core.cpp.
 {}
Member Function Documentation
assembleScene()
void Core::assembleScene (const std::string & filename)
Function to assemble the scene.
Parameters
filename The name of the file to assemble.
This function call the parsing function to assemble the scene.
Definition at line 30 of file Core.cpp.
 {
     Logger* logger = LoggerSingleton::getInstance();
     SceneBuilder sceneBuilder;
     try {
         Parsing parser(filename);
         logger->log(DEBUG, "Parsing done.");
         sceneBuilder.createCamera(parser.GetCamera());
         logger->log(DEBUG, "Camera created.");
         sceneBuilder.createLight(parser.getLights());
         logger->log(DEBUG, "Light created.");
         sceneBuilder.createPrimitives(parser.getPrimitives());
         logger->log(DEBUG, "Primitives Created.");
         sceneBuilder.createMeshFromObj(parser.getObj());
         logger->log(DEBUG, "Meshes Created.");
         this->scene = sceneBuilder.getScene();
     }
     catch(const Exception& e) {
         std::cerr << e.what() << '\n';
         logger->log(ERROR, "An error occurred during scene assembly: " + std::string(e.what()));
         throw Exception("An error occurred during scene assembly: " + std::string(e.what()), Level::HIGH);
     }
 }
References SceneBuilder::createCamera(), SceneBuilder::createLight(), SceneBuilder::createMeshFromObj(), SceneBuilder::createPrimitives(), DEBUG, ERROR, Parsing::GetCamera(), LoggerSingleton::getInstance(), Parsing::getLights(), Parsing::getObj(), Parsing::getPrimitives(), SceneBuilder::getScene(), HIGH, Logger::log(), scene, and Exception::what().
Referenced by generatePPM(), and main().
generatePPM()
void Core::generatePPM ()
Function to generate the PPM file.
Definition at line 62 of file Core.cpp.
 {
     Compute potatRaycer = Compute(this->getScene());
     Logger* logger = LoggerSingleton::getInstance();
     try {
         potatRaycer.loop(this->getScene());
     } catch(const ObserverException& e) {
         std::cout << "Config changed, reloading: " << e.what() << std::endl;
         std::this_thread::sleep_for(std::chrono::seconds(5));
         FileWatcher *watcher = FileWatcherSingleton::getInstance();
         this->assembleScene(watcher->getFile());
         this->generatePPM();
     } catch(const Exception& e) {
         std::cout << "Error: " << e.what() << std::endl;
         logger->log(ERROR, "An error occurred during PPM generation: " + std::string(e.what()));
         throw Exception("An error occurred during PPM generation: " + std::string(e.what()), Level::HIGH);
     }
 }
References assembleScene(), ERROR, FileWatcher::getFile(), LoggerSingleton::getInstance(), FileWatcherSingleton::getInstance(), getScene(), HIGH, Logger::log(), Compute::loop(), and Exception::what().
Referenced by main().
getScene()
const Scene & Core::getScene () const
Function to get the scene.
Returns
The scene.
Definition at line 81 of file Core.cpp.
 {
     return this->scene;
 }
References scene.
Referenced by generatePPM().
Member Data Documentation
scene
Scene Core::scene private
Definition at line 49 of file Core.hpp.
Referenced by assembleScene(), Core(), and getScene().
The documentation for this class was generated from the following files:
src/Core/Core.hpp
src/Core/Core.cpp