PotatRaycer: src/Vec3/Vec3.hpp File Reference
Vec3.hpp File Reference
Vec3 class header file.
#include "include.hpp"
#include "SingletonLogger.hpp"
Classes
class Vec3
Class for representing a 3D vector.
Functions
std::istream & operator>> (std::istream &is, Vec3 &t)
std::ostream & operator<< (std::ostream &os, const Vec3 &t)
Vec3 operator+ (const Vec3 &v1, const Vec3 &v2)
Vec3 operator- (const Vec3 &v1, const Vec3 &v2)
Vec3 operator* (const Vec3 &v1, const Vec3 &v2)
Vec3 operator/ (const Vec3 &v1, const Vec3 &v2)
Vec3 operator* (float t, const Vec3 &v)
Vec3 operator* (const Vec3 &v, float t)
Vec3 operator/ (float t, const Vec3 &v)
Vec3 operator/ (const Vec3 &v, float t)
float dot (const Vec3 &v1, const Vec3 &v2)
Vec3 cross (const Vec3 &v1, const Vec3 &v2)
Vec3 unit_vector (Vec3 v)
Get the unit vector of a Vec3.
Vec3 reflect (const Vec3 &v, const Vec3 &n)
Reflect a vector off a surface with a given normal.
bool refract (const Vec3 &v, const Vec3 &n, float ni_over_nt, Vec3 &refracted)
Refract a vector through a surface with a given normal and refraction index.
float schlick (float cosine, float ref_idx)
Compute the Schlick approximation for reflectance.
Vec3 random_in_unit_sphere ()
Generate a random vector inside a unit sphere.
Vec3 random_in_unit_disk ()
Generate a random vector inside a unit disk.
Detailed Description
Vec3 class header file.
Definition in file Vec3.hpp.
Function Documentation
cross()
Vec3 cross (const Vec3 & v1, const Vec3 & v2) inline
Definition at line 219 of file Vec3.hpp.
{
     return Vec3(v1.e[1] * v2.e[2] - v1.e[2] * v2.e[1],
                 -(v1.e[0] * v2.e[2] - v1.e[2] * v2.e[0]),
                 v1.e[0] * v2.e[1] - v1.e[1] * v2.e[0]);
 }
References Vec3::e.
Referenced by Camera::Camera(), and Triangle::hit().
dot()
float dot (const Vec3 & v1, const Vec3 & v2) inline
Definition at line 215 of file Vec3.hpp.
{
     return v1[0] * v2[0] + v1[1] * v2[1] + v1[2] * v2[2];
 }
Referenced by Circle::hit(), Sphere::hit(), Triangle::hit(), Plane::hit(), random_in_unit_disk(), reflect(), refract(), Texture::scatter(), Dielectric::scatter(), and Lambertian::scatter().
operator*() [1/3]
Vec3 operator* (const Vec3 & v, float t) inline
Definition at line 203 of file Vec3.hpp.
{
     return Vec3(t * v.e[0], t * v.e[1], t * v.e[2]);
 }
References Vec3::e.
operator*() [2/3]
Vec3 operator* (const Vec3 & v1, const Vec3 & v2) inline
Definition at line 191 of file Vec3.hpp.
{
     return Vec3(v1.e[0] * v2.e[0], v1.e[1] * v2.e[1], v1.e[2] * v2.e[2]);
 }
References Vec3::e.
operator*() [3/3]
Vec3 operator* (float t, const Vec3 & v) inline
Definition at line 199 of file Vec3.hpp.
{
     return Vec3(t * v.e[0], t * v.e[1], t * v.e[2]);
 }
References Vec3::e.
operator+()
Vec3 operator+ (const Vec3 & v1, const Vec3 & v2) inline
Definition at line 183 of file Vec3.hpp.
{
     return Vec3(v1.e[0] + v2.e[0], v1.e[1] + v2.e[1], v1.e[2] + v2.e[2]);
 }
References Vec3::e.
operator-()
Vec3 operator- (const Vec3 & v1, const Vec3 & v2) inline
Definition at line 187 of file Vec3.hpp.
{
     return Vec3(v1.e[0] - v2.e[0], v1.e[1] - v2.e[1], v1.e[2] - v2.e[2]);
 }
References Vec3::e.
operator/() [1/3]
Vec3 operator/ (const Vec3 & v, float t) inline
Definition at line 211 of file Vec3.hpp.
{
     return Vec3(v.e[0] / t, v.e[1] / t, v.e[2] / t);
 }
References Vec3::e.
operator/() [2/3]
Vec3 operator/ (const Vec3 & v1, const Vec3 & v2) inline
Definition at line 195 of file Vec3.hpp.
{
     return Vec3(v1.e[0] / v2.e[0], v1.e[1] / v2.e[1], v1.e[2] / v2.e[2]);
 }
References Vec3::e.
operator/() [3/3]
Vec3 operator/ (float t, const Vec3 & v) inline
Definition at line 207 of file Vec3.hpp.
{
     return Vec3(t / v.e[0], t / v.e[1], t / v.e[2]);
 }
References Vec3::e.
operator<<()
std::ostream& operator<< (std::ostream & os, const Vec3 & t) inline
Definition at line 173 of file Vec3.hpp.
{
     os << t.e[0] << " " << t.e[1] << " " << t.e[2];
     return os;
 }
References Vec3::e.
operator>>()
std::istream& operator>> (std::istream & is, Vec3 & t) inline
Definition at line 168 of file Vec3.hpp.
{
     is >> t.e[0] >> t.e[1] >> t.e[2];
     return is;
 }
References Vec3::e.
random_in_unit_disk()
Vec3 random_in_unit_disk () inline
Generate a random vector inside a unit disk.
Returns
A random vector inside a unit disk.
Definition at line 337 of file Vec3.hpp.
{
     Vec3 p;
     do {
         p = 2.0 * Vec3(drand48(), drand48(), 0.0) - Vec3(1, 1, 0);
     } while (dot(p, p) >= 1.0);
     return p;
 }
References dot().
Referenced by Camera::get_Ray().
random_in_unit_sphere()
Vec3 random_in_unit_sphere () inline
Generate a random vector inside a unit sphere.
Returns
A random vector inside a unit sphere.
Definition at line 324 of file Vec3.hpp.
{
     Vec3 p;
     do {
         p = 2.9 * Vec3(drand48(), drand48(), drand48()) - Vec3(1, 1, 1);
     } while (p.length_squared() >= 1.0);
     return p;
 }
References Vec3::length_squared().
Referenced by Texture::scatter(), Lambertian::scatter(), and Metal::scatter().
reflect()
Vec3 reflect (const Vec3 & v, const Vec3 & n) inline
Reflect a vector off a surface with a given normal.
Parameters
v The incident vector.
n The normal vector of the surface.
Returns
The reflected vector.
Definition at line 282 of file Vec3.hpp.
{
     return v - 2 * dot(v, n) * n;
 }
References dot().
Referenced by Texture::scatter(), Dielectric::scatter(), and Metal::scatter().
refract()
bool refract (const Vec3 & v, const Vec3 & n, float ni_over_nt, Vec3 & refracted) inline
Refract a vector through a surface with a given normal and refraction index.
Parameters
v The incident vector.
n The normal vector of the surface.
ni_over_nt The ratio of the indices of refraction.
refracted The refracted vector (output parameter).
Returns
True if refraction is possible, false otherwise.
Definition at line 295 of file Vec3.hpp.
{
     Vec3 uv = unit_vector(v);
     float dt = dot(uv, n);
     float discriminant = 1.0 - ni_over_nt * ni_over_nt * (1 - dt * dt);
     if (discriminant > 0) {
         refracted = ni_over_nt * (uv - n * dt) - n * sqrt(discriminant);
         return true;
     }
     return false;
 }
References dot(), and unit_vector().
Referenced by Dielectric::scatter().
schlick()
float schlick (float cosine, float ref_idx) inline
Compute the Schlick approximation for reflectance.
Parameters
cosine The cosine of the angle of incidence.
ref_idx The index of refraction.
Returns
The approximated reflectance.
Definition at line 313 of file Vec3.hpp.
{
     float r0 = (1 - ref_idx) / (1 + ref_idx);
     r0 = r0 * r0;
     return r0 + (1 - r0) * pow((1 - cosine), 5);
 }
Referenced by Dielectric::scatter().
unit_vector()
Vec3 unit_vector (Vec3 v) inline
Get the unit vector of a Vec3.
Parameters
v The vector to normalize.
Returns
The unit vector.
Definition at line 271 of file Vec3.hpp.
{
     return v / v.length();
 }
References Vec3::length().
Referenced by AmbiantLight::calculateLightDirection(), DirectionalLight::calculateLightDirection(), Camera::Camera(), refract(), Texture::scatter(), and Metal::scatter().