name: Unit_tests
on:
  push:
    branches:
      - main

jobs:
  DARIUS_PRESIDENT:
    runs-on: ubuntu-latest
    steps:
      - name: DARIUS_AER
        uses: actions/checkout@v2

      - name: DARIUS_APE
        run: ./install_criterion.sh

      - name: DARIUS_EPSEED
        run: |
          sudo apt update
          sudo apt install -y gcovr
          sudo apt-get install -y libconfig-dev

      - name: Install libconfig from source
        run: |
          sudo apt update
          sudo apt install -y build-essential
          wget https://hyperrealm.github.io/libconfig/dist/libconfig-1.7.2.tar.gz
          tar -xvzf libconfig-1.7.2.tar.gz
          cd libconfig-1.7.2
          ./configure
          make
          sudo make install

      - name: Check libconfig installation
        run: |
          dpkg -L libconfig-dev

      - name: DARIUS_SHINY
        run: |
          make test
          ./tests/run_tests || true
          gcovr -r . --xml -o coverage.xml || true

